// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4I0Js9fM1rG1_QVRLGPlii12yhrKScbk',
    appId: '1:674317899233:web:53b58d9037c52ab332eea0',
    messagingSenderId: '674317899233',
    projectId: 'fir-sns-app',
    authDomain: 'fir-sns-app.firebaseapp.com',
    storageBucket: 'fir-sns-app.appspot.com',
    measurementId: 'G-GMLV2SS51T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_L28r9aGQm_AYO7vzYFzQsspd-Qz8oNY',
    appId: '1:674317899233:android:231a9bfe57d10b0932eea0',
    messagingSenderId: '674317899233',
    projectId: 'fir-sns-app',
    storageBucket: 'fir-sns-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejXrhRw9Y0KojVjMN7-SmN-4dq5Ql9io',
    appId: '1:674317899233:ios:4e41bd1ef13e87a432eea0',
    messagingSenderId: '674317899233',
    projectId: 'fir-sns-app',
    storageBucket: 'fir-sns-app.appspot.com',
    iosClientId: '674317899233-amoj0mlrnt0hcftagra1egaods1em95f.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoSnsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejXrhRw9Y0KojVjMN7-SmN-4dq5Ql9io',
    appId: '1:674317899233:ios:4e41bd1ef13e87a432eea0',
    messagingSenderId: '674317899233',
    projectId: 'fir-sns-app',
    storageBucket: 'fir-sns-app.appspot.com',
    iosClientId: '674317899233-amoj0mlrnt0hcftagra1egaods1em95f.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoSnsApp',
  );
}
